//concole.error("Esto es un error");
console.error("Esto es una advertencia");
//console.info("Esto es una información");
console.info("Esto es una información");
//console.log("Hola mundo");
console.log("Hola mundo");
//console.warn("Esto es una advertencia");
console.warn("Esto es una advertencia");
//console.table(["Hola", "mundo", "en", "una", "tabla"]);
console.table(["Hola", "mundo", "en", "una", "tabla"]);
//console.dir({nombre: "Niverl", edad: 18, profesion: "Desarrollador"});
console.dir({nombre: "Niverl", edad: 18, profesion: "Desarrollador"});
//console.count("Veces que se ha llamado a console.count");
console.count("Veces que se ha llamado a console.count");
console.count("Veces que se ha llamado a console.count");
console.count("Veces que se ha llamado a console.count");
//console.group("Grupo de mensajes");
console.group("Grupo de mensajes");
console.log("Mensaje 1");
console.log("Mensaje 2");
console.log("Mensaje 3");
//console.groupEnd("Grupo de mensajes");
console.groupEnd("Grupo de mensajes");
//console.groupCollapsed("Grupo colapsado");
console.groupCollapsed("Grupo colapsado");
console.log("Mensaje colapsado 1");
console.log("Mensaje colapsado 2");
console.log("Mensaje colapsado 3");
//console.time("Tiempo de ejecución");
console.time("Tiempo de ejecución");
console.timeLog();